from pathlib import Path
import re, html, json, textwrap, datetime
root=Path('/mnt/data/course_update')
base='https://learn-quran-onlin.github.io/QuranGuides/'
wa='https://wa.me/201009517839?text=Assalamu%20Alaikum%2C%20I%20would%20like%20to%20book%20a%20free%20trial%20Quran%20class.'
# Extract header/footer from current courses page
cur=(root/'courses.html').read_text(encoding='utf-8')
header=cur.split('<main>')[0]
footer='</main>'+cur.split('</main>',1)[1]
# update active nav per page

def set_active(h, file):
    h=re.sub(r'<a href="([^"]+)" class="active">', r'<a href="\1" class="">', h)
    h=h.replace(f'<a href="{file}" class="">', f'<a href="{file}" class="active">')
    return h

courses=[
    dict(slug='quran-reading', title='Online Quran Reading Classes', category='Quran Reading', icon='📖', audience='children, adults, beginners, and non-Arabic speakers', level='Beginner to intermediate', duration='Flexible monthly plan', desc='Build the foundations of Quran reading from Arabic letters and short vowels to joining letters, reading Quranic words, and reciting short surahs with confidence.', learn=['Recognize Arabic letters in isolated, beginning, middle, and ending forms','Read short vowels, sukoon, shaddah, tanween, and madd step by step','Join letters correctly and read Quranic words without guessing','Move from simple words to short ayat and selected short surahs','Improve fluency through guided repetition and gentle live correction'], ideal=['Young children starting Quran reading','Adults who never learned Arabic reading properly','Students who know letters but read slowly','Families who want a structured foundation before Tajweed'], outcomes=['read Quranic words more confidently','recognize common reading patterns','recite short surahs with fewer pauses','be ready to begin practical Tajweed'], related=['tajweed','noor-al-bayan','noorani-qaida','quran-for-kids']),
    dict(slug='noor-al-bayan', title='Noor Al-Bayan Course', category='Arabic Reading Foundations', icon='🌟', audience='kids, beginners, and new Quran readers', level='Beginner', duration='Step-by-step private lessons', desc='A clear phonics-based course that teaches Arabic letters, sounds, harakat, syllables, joining, and early Quran reading in a gradual way.', learn=['Master Arabic letters and their sounds using a simple phonetic method','Understand fatha, kasra, damma, sukoon, shaddah, tanween, and madd','Read syllables, words, and short sentences in a smooth progression','Practice examples from Arabic and Quranic reading contexts','Build the foundation needed for Quran reading and Tajweed'], ideal=['Children who need a simple reading method','Beginners who want Arabic reading before full Quran recitation','Students who mix up letters or vowels','Parents who want a clear step-by-step plan'], outcomes=['decode Arabic words independently','read from right to left with confidence','prepare for Quran recitation lessons','build stronger pronunciation habits'], related=['quran-reading','noorani-qaida','arabic-reading-writing','tajweed']),
    dict(slug='noorani-qaida', title='Noorani Qaida Course', category='Quran Reading Foundations', icon='🔤', audience='beginners who want to read Quran correctly', level='Beginner', duration='Flexible pace', desc='Learn Quran reading foundations through the well-known Qaida approach: letters, sounds, vowels, joining, rules, and practice words.', learn=['Read Arabic letters with correct pronunciation','Practice joining letters and reading words gradually','Understand basic Quran reading signs and symbols','Prepare for recitation from the Mushaf','Develop accuracy before speed'], ideal=['Beginners of any age','Children before starting full Quran recitation','Students who need a stronger base','Non-Arabic speakers learning Quran reading'], outcomes=['read basic Quranic words','recognize vowel patterns','avoid common beginner mistakes','move into short surah recitation'], related=['noor-al-bayan','quran-reading','tajweed','quran-for-beginners']),
    dict(slug='tajweed', title='Online Tajweed Classes', category='Tajweed', icon='✨', audience='students who can read Quran and want cleaner recitation', level='Beginner to advanced', duration='Ongoing improvement plan', desc='Improve Quran recitation with practical Tajweed rules applied directly while reading, including makharij, sifaat, madd, ghunnah, qalqalah, noon sakinah, meem sakinah, and more.', learn=['Pronounce letters from the correct makhraj','Apply Tajweed rules during real recitation, not only in theory','Understand madd, ghunnah, qalqalah, ikhfa, idgham, izhar, and iqlab','Correct common mistakes in heavy/light letters','Develop a measured, confident recitation style'], ideal=['Students who can read but make Tajweed mistakes','Adults wanting to improve recitation','Children moving beyond basic reading','Learners preparing for memorization'], outcomes=['recite with clearer pronunciation','apply core Tajweed rules naturally','notice and correct mistakes faster','feel more confident reading aloud'], related=['advanced-tajweed','quran-reading','hifz','ijazah-preparation']),
    dict(slug='advanced-tajweed', title='Advanced Tajweed & Recitation Coaching', category='Advanced Tajweed', icon='🎙️', audience='intermediate and advanced Quran readers', level='Intermediate to advanced', duration='Personal coaching plan', desc='A focused recitation-improvement course for learners who already know the basics and want refinement, fluency, rhythm, stronger makharij, and consistent application.', learn=['Refine difficult letter exits and qualities','Improve rhythm, pauses, starts, and breath control','Identify hidden mistakes in daily recitation','Strengthen practical application of rules across longer passages','Build a personal correction log and revision plan'], ideal=['Students with basic Tajweed knowledge','Hifz students needing cleaner recitation','Adults preparing for advanced study','Learners who want detailed correction'], outcomes=['recite longer passages more smoothly','reduce repeated mistakes','improve clarity and confidence','prepare for ijazah-style discipline'], related=['tajweed','ijazah-preparation','hifz-revision','hifz']),
    dict(slug='hifz', title='Online Hifz & Quran Memorization Classes', category='Hifz', icon='🌙', audience='kids, teens, and adults memorizing Quran', level='All levels', duration='Long-term memorization plan', desc='Memorize Quran online with a realistic plan that balances new memorization, recent revision, old revision, testing, and parent/student progress tracking.', learn=['Memorize new ayat using repetition and listening methods','Revise recent pages before they become weak','Build an old-revision cycle that protects previous memorization','Learn how to fix similar ayat and common mistakes','Track progress through regular testing and feedback'], ideal=['Children beginning Juz Amma or longer memorization','Adults returning to Hifz after a break','Students who memorize but forget quickly','Families who need a steady revision system'], outcomes=['memorize with less stress','retain previous portions better','follow a weekly revision structure','develop consistency and confidence'], related=['hifz-revision','juz-amma-revision','tajweed','quran-for-kids']),
    dict(slug='hifz-revision', title='Hifz Revision & Quran Retention Course', category='Memorization Revision', icon='🔁', audience='students who memorized before but need stronger revision', level='All levels', duration='Custom revision cycle', desc='A practical revision course designed for learners who forget previous memorization, feel overwhelmed, or need a clear system to strengthen old pages.', learn=['Diagnose weak portions and repeated mistakes','Create a daily and weekly revision schedule','Separate new memorization from old revision','Use testing days to measure retention','Learn how to restart Hifz after a break'], ideal=['Students who forget Juz Amma','Huffaz needing structured review','Adults restarting memorization','Children who need accountability'], outcomes=['know exactly what to revise each week','reduce forgotten pages','feel less overwhelmed','rebuild confidence in Hifz'], related=['hifz','juz-amma-revision','tajweed','quran-for-adults']),
    dict(slug='juz-amma-revision', title='Juz Amma Revision Course', category='Short Surah Revision', icon='🕋', audience='children and adults revising short surahs', level='Beginner to intermediate', duration='Short focused program', desc='Strengthen Juz Amma recitation and memorization through repeated review, Tajweed correction, meaning reminders, and mistake tracking.', learn=['Revise short surahs in a clear order','Correct pronunciation and Tajweed mistakes','Build confidence reciting from memory','Review similar endings and repeated words','Add brief meaning reminders to improve connection'], ideal=['Children who memorized Juz Amma before','Adults revising short surahs for prayer','Students preparing for stronger Hifz','Families wanting a manageable Quran goal'], outcomes=['recite short surahs with confidence','remember weak surahs better','improve prayer recitation','prepare for the next memorization stage'], related=['hifz','hifz-revision','quran-reading','tajweed']),
    dict(slug='quran-for-kids', title='Online Quran Classes for Kids', category='Kids Quran Classes', icon='👧', audience='children from beginner to advanced levels', level='Beginner to advanced', duration='Flexible weekly classes', desc='Child-friendly private Quran lessons with patient teachers, interactive practice, repetition, rewards, parent updates, and a plan that fits the child’s age and level.', learn=['Read Arabic letters and Quranic words step by step','Recite short surahs with correction and encouragement','Learn basic Tajweed in a child-friendly way','Memorize according to a realistic weekly plan','Develop love and respect for the Quran'], ideal=['Young children starting Quran learning','Kids who need patient correction','Homeschool families','Parents who want regular feedback'], outcomes=['enjoy Quran lessons more','read and recite with more confidence','build a steady routine','make visible progress parents can follow'], related=['quran-reading','noor-al-bayan','juz-amma-revision','islamic-studies']),
    dict(slug='quran-for-adults', title='Online Quran Classes for Adults', category='Adult Quran Classes', icon='🧑', audience='busy adults and beginners', level='Beginner to advanced', duration='Flexible schedule', desc='Private Quran classes for adults who want to improve reading, Tajweed, memorization, or Quranic Arabic with a respectful pace and flexible timing.', learn=['Start from your actual level without embarrassment','Correct long-standing pronunciation mistakes','Build a realistic practice routine around work and family','Learn Tajweed gradually while reciting','Choose reading, memorization, Arabic, or mixed goals'], ideal=['Adults starting later in life','Busy professionals','Reverts and non-Arabic speakers','Students who want private correction'], outcomes=['feel confident reading aloud','understand your mistakes clearly','keep a sustainable weekly routine','move steadily toward your Quran goals'], related=['tajweed','quran-reading','quran-for-reverts','conversational-arabic']),
    dict(slug='quran-for-reverts', title='Online Quran Classes for Reverts', category='New Muslim Quran Learning', icon='🤲', audience='new Muslims and beginners', level='Beginner-friendly', duration='Gentle step-by-step plan', desc='A welcoming Quran course for reverts and new Muslims, starting from Arabic sounds, short surahs for prayer, essential duas, and basic Islamic understanding.', learn=['Learn Arabic letters and sounds gently','Practice Al-Fatihah and short surahs for prayer','Understand essential meanings and daily duas','Ask questions in a respectful private space','Build confidence without pressure'], ideal=['New Muslims with no Arabic background','Reverts learning prayer recitation','Adults who need gentle foundations','Learners who prefer private 1-to-1 support'], outcomes=['recite basic prayer surahs more confidently','understand essential Quran learning steps','feel supported and not rushed','build a long-term learning plan'], related=['quran-reading','islamic-studies','quran-for-adults','tajweed']),
    dict(slug='ijazah-preparation', title='Quran Ijazah Preparation Course', category='Ijazah Preparation', icon='📜', audience='advanced reciters seeking disciplined preparation', level='Advanced', duration='Assessment-based', desc='A preparation path for advanced students who want to polish recitation, strengthen precision, and become ready for ijazah-level expectations.', learn=['Refine recitation accuracy at a detailed level','Strengthen Tajweed application across long passages','Follow a disciplined correction and revision routine','Prepare for teacher evaluation and high standards','Develop consistency, patience, and precision'], ideal=['Advanced Tajweed students','Hifz students with strong fluency','Aspiring Quran teachers','Learners seeking serious recitation discipline'], outcomes=['understand ijazah expectations','improve accuracy and consistency','prepare for advanced teacher review','build a stronger recitation routine'], related=['advanced-tajweed','tajweed','hifz','hifz-revision']),
    dict(slug='arabic-reading-writing', title='Arabic Reading & Writing Course', category='Arabic Foundations', icon='✍️', audience='children and adults learning Arabic literacy', level='Beginner to intermediate', duration='Progressive levels', desc='Learn Arabic letters, handwriting, joining letters, word reading, sentence reading, spelling, and simple comprehension through guided practice.', learn=['Recognize and write Arabic letters in all positions','Connect letters correctly in handwriting and reading','Read words and short sentences with confidence','Practice spelling, dictation, and simple comprehension','Build a strong base before Quranic Arabic or conversation'], ideal=['Children learning Arabic literacy','Adults who read slowly','Students who need writing practice','Learners preparing for Arabic or Quran studies'], outcomes=['read and write Arabic letters accurately','understand basic sentence structure','improve spelling and handwriting','move into Arabic conversation or Quranic Arabic'], related=['arabic','noor-al-bayan','conversational-arabic','arabic-for-kids']),
    dict(slug='arabic', title='Quranic Arabic Classes', category='Quranic Arabic', icon='🔤', audience='students who want to understand more Quran vocabulary and grammar', level='Beginner to intermediate', duration='Structured levels', desc='Learn high-frequency Quranic words, pronouns, prepositions, particles, basic grammar, and simple translation skills to understand more of what you recite.', learn=['Recognize common Quranic words and repeated patterns','Understand pronouns, prepositions, particles, and question words','Learn basic verb patterns gradually','Translate simple ayat with teacher guidance','Connect grammar with real Quran examples'], ideal=['Quran readers who want understanding','Adults and teens','Students who know basic Arabic reading','Learners preparing for deeper tafsir study'], outcomes=['understand repeated Quran vocabulary','recognize sentence patterns','connect recitation with meaning','build a foundation for deeper Arabic study'], related=['arabic-reading-writing','conversational-arabic','quran-reading','islamic-studies']),
    dict(slug='conversational-arabic', title='Conversational Arabic Course', category='Spoken Arabic', icon='💬', audience='students who want to speak and understand Arabic in daily situations', level='Beginner to intermediate', duration='Conversation-focused plan', desc='Build practical speaking confidence through everyday dialogues, listening practice, useful vocabulary, sentence patterns, and guided conversation.', learn=['Introduce yourself and speak about family, school, work, and daily life','Ask and answer common questions naturally','Build vocabulary through real situations','Improve listening and pronunciation','Practice short guided conversations every class'], ideal=['Adults who want practical Arabic','Teens and children building speaking confidence','Students preparing for travel or community use','Learners who prefer active conversation'], outcomes=['speak in simple Arabic conversations','understand common phrases','respond with more confidence','build a useful vocabulary base'], related=['arabic','arabic-for-adults','arabic-for-kids','business-arabic']),
    dict(slug='arabic-for-kids', title='Arabic for Kids Course', category='Kids Arabic', icon='🎒', audience='children learning Arabic as a second language', level='Beginner to intermediate', duration='Age-based levels', desc='A child-friendly Arabic course with letters, words, simple sentences, listening, speaking, writing, games, and short reading activities.', learn=['Learn letters, sounds, and common words','Practice speaking through simple questions and answers','Read short age-appropriate sentences','Write letters and basic words','Build confidence through repetition and activities'], ideal=['Children learning Arabic online','Families outside Arabic-speaking countries','Kids who need fun structured lessons','Students preparing for Quranic Arabic later'], outcomes=['recognize and use common Arabic words','speak in simple sentences','read short Arabic texts','enjoy Arabic learning more'], related=['arabic-reading-writing','conversational-arabic','noor-al-bayan','quran-for-kids']),
    dict(slug='arabic-for-adults', title='Arabic for Adults Course', category='Adult Arabic', icon='🗣️', audience='adults who want structured Arabic learning', level='Beginner to intermediate', duration='Flexible adult schedule', desc='A practical Arabic course for adults covering reading, vocabulary, grammar, conversation, listening, and Quran-related language foundations.', learn=['Start Arabic from your current level','Build vocabulary and sentence patterns','Practice conversation and listening','Understand basic grammar without confusion','Choose Quranic, conversational, or professional focus'], ideal=['Adults starting Arabic later','Busy professionals','Reverts and non-Arabic speakers','Learners who want clear structure'], outcomes=['read and understand simple Arabic','hold basic conversations','use grammar more confidently','continue into Quranic or professional Arabic'], related=['conversational-arabic','quranic-arabic','business-arabic','financial-arabic']),
    dict(slug='business-arabic', title='Business Arabic Course', category='Professional Arabic', icon='💼', audience='professionals, entrepreneurs, customer support teams, and students', level='Intermediate recommended', duration='Goal-based modules', desc='Learn Arabic for business communication, meetings, introductions, emails, customer conversations, presentations, negotiation vocabulary, and professional etiquette.', learn=['Use Arabic in introductions, meetings, and workplace conversations','Write simple professional messages and emails','Understand common business terms and polite expressions','Practice customer service and sales conversations','Build confidence for work with Arabic-speaking clients'], ideal=['Professionals working with Arabic-speaking clients','Business owners and freelancers','Customer support or sales teams','Students preparing for Arabic-speaking workplaces'], outcomes=['handle basic business conversations','write clearer professional messages','understand workplace vocabulary','communicate more confidently with clients'], related=['conversational-arabic','financial-arabic','arabic-for-adults','arabic']),
    dict(slug='financial-arabic', title='Financial Arabic Course', category='Arabic for Finance', icon='💰', audience='finance, accounting, banking, and business learners', level='Intermediate recommended', duration='Specialized modules', desc='A focused Arabic course for financial vocabulary and communication, including numbers, invoices, payments, reports, banking terms, budgeting, and client discussions.', learn=['Use Arabic numbers, amounts, dates, and payment terms accurately','Understand financial documents, invoices, and simple reports','Practice banking, accounting, budgeting, and transaction vocabulary','Discuss prices, fees, transfers, and payment plans politely','Build a specialized glossary for finance-related work'], ideal=['Accountants and finance students','Business owners managing Arabic payments','Professionals in banking or customer service','Learners needing Arabic for invoices and reports'], outcomes=['understand key financial Arabic terms','discuss payments and invoices more clearly','read basic financial documents','communicate with finance-related confidence'], related=['business-arabic','conversational-arabic','arabic-for-adults','arabic']),
    dict(slug='islamic-studies', title='Online Islamic Studies Classes', category='Islamic Studies', icon='🕌', audience='children, teens, and adults', level='Beginner to intermediate', duration='Age-appropriate levels', desc='Study essential Islamic knowledge in a simple structured way, including Aqeedah, Seerah, Hadith, duas, manners, worship, and character-building lessons.', learn=['Learn basic Aqeedah in a clear age-appropriate way','Study Seerah lessons and prophetic character','Memorize daily duas and understand when to use them','Learn worship basics and Islamic manners','Connect knowledge with daily life and behavior'], ideal=['Children needing Islamic Studies online','Families wanting structured religious education','Reverts learning foundations','Teens and adults seeking basics'], outcomes=['understand core Islamic concepts','apply manners and duas in daily life','learn Seerah lessons practically','build stronger Islamic identity'], related=['seerah','hadith-dua-manners','aqeedah','quran-for-reverts']),
    dict(slug='seerah', title='Seerah Course for Kids & Adults', category='Seerah', icon='🌺', audience='students who want to learn the life of the Prophet ﷺ', level='Beginner-friendly', duration='Story-based modules', desc='Learn the life of Prophet Muhammad ﷺ through meaningful stories, lessons, manners, patience, courage, mercy, and practical application in daily life.', learn=['Study key events from the Seerah in order','Extract practical lessons from each stage','Understand the Prophet’s ﷺ manners and character','Connect Seerah with modern daily life','Build love and respect for the Prophet ﷺ'], ideal=['Children learning Islamic history','Adults wanting a structured Seerah overview','Families seeking character-building lessons','Students who enjoy story-based learning'], outcomes=['know key Seerah events','understand prophetic character','apply lessons in daily behavior','increase love for the Prophet ﷺ'], related=['islamic-studies','hadith-dua-manners','aqeedah','quran-for-kids']),
    dict(slug='hadith-dua-manners', title='Hadith, Duas & Islamic Manners Course', category='Character & Worship', icon='🤍', audience='kids, teens, and families', level='Beginner-friendly', duration='Weekly practical lessons', desc='A practical course teaching short hadith, daily duas, Islamic manners, worship habits, and character lessons students can apply at home and school.', learn=['Memorize important daily duas','Learn short hadith with simple explanations','Practice Islamic manners in real situations','Understand worship habits and daily routines','Build a positive Muslim character step by step'], ideal=['Children and teens','Families wanting practical Islamic habits','Reverts learning daily duas','Students who benefit from short lessons'], outcomes=['use daily duas more regularly','understand short hadith meanings','show better manners and habits','connect Islamic knowledge to daily life'], related=['islamic-studies','seerah','aqeedah','quran-for-kids']),
    dict(slug='aqeedah', title='Aqeedah Basics Course', category='Islamic Belief', icon='🛡️', audience='children, reverts, and beginners', level='Beginner-friendly', duration='Structured foundations', desc='Learn the foundations of Islamic belief in a clear and gentle way, including belief in Allah, angels, books, messengers, the Last Day, and Qadar.', learn=['Understand the pillars of iman in simple language','Learn about Allah with reverence and clarity','Study belief in messengers, books, angels, and the Hereafter','Ask questions in a safe learning environment','Connect belief with worship and character'], ideal=['Children learning Islamic foundations','Reverts and new Muslims','Adults reviewing basics','Families wanting clear Aqeedah lessons'], outcomes=['understand the pillars of iman','answer basic belief questions','connect faith with daily worship','build stronger Islamic confidence'], related=['islamic-studies','seerah','hadith-dua-manners','quran-for-reverts']),
]
by_slug={c['slug']:c for c in courses}

def meta_desc(c):
    return f"{c['title']} for {c['audience']}. Learn course overview, objectives, ideal learners, features, outcomes, and book a free trial on WhatsApp."

def course_schema(c):
    return json.dumps({"@context":"https://schema.org","@type":"Course","name":c['title'],"description":meta_desc(c),"provider":{"@type":"Organization","name":"Quran.com Online Academy","telephone":"+201009517839","url":base},"educationalLevel":c['level'],"offers":{"@type":"Offer","url":base+c['slug']+'.html',"availability":"https://schema.org/InStock","category":"Online Quran and Arabic classes"}}, ensure_ascii=False)

def faq_schema(c):
    faqs=[
        (f"Who is the {c['title']} for?", f"This course is suitable for {c['audience']}. The teacher assesses the learner and adjusts the plan to the student’s level."),
        ("How are the classes conducted?", "Classes are private online lessons with live teacher correction, structured practice, and progress follow-up. Enrollment is handled through WhatsApp."),
        ("Can I combine this course with another subject?", "Yes. Students can combine Quran reading, Tajweed, Hifz, Arabic, or Islamic Studies depending on their goals and schedule."),
    ]
    return json.dumps({"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}} for q,a in faqs]}, ensure_ascii=False)

def course_page(c):
    title = f"{c['title']} | Quran.com Online Academy"
    desc = meta_desc(c)
    related_html=''.join(f'<a class="related-pill" href="{r}.html">{html.escape(by_slug.get(r,{}).get("title",r.replace("-"," ").title()))}</a>' for r in c['related'] if r in by_slug)
    learn=''.join(f'<li>{html.escape(x)}</li>' for x in c['learn'])
    ideal=''.join(f'<li>{html.escape(x)}</li>' for x in c['ideal'])
    outcomes=''.join(f'<li>{html.escape(x)}</li>' for x in c['outcomes'])
    # Override head
    h=set_active(header, c['slug']+'.html')
    h=re.sub(r'<title>.*?</title>', f'<title>{html.escape(title)}</title>', h, flags=re.S)
    h=re.sub(r'<meta name="description" content=".*?"/>', f'<meta name="description" content="{html.escape(desc)}"/>', h, flags=re.S)
    h=re.sub(r'<link rel="canonical" href=".*?"/>', f'<link rel="canonical" href="{base}{c["slug"]}.html"/>', h)
    h=re.sub(r'<meta property="og:title" content=".*?"/>', f'<meta property="og:title" content="{html.escape(title)}"/>', h)
    h=re.sub(r'<meta property="og:description" content=".*?"/>', f'<meta property="og:description" content="{html.escape(desc)}"/>', h)
    h=re.sub(r'<meta property="og:url" content=".*?"/>', f'<meta property="og:url" content="{base}{c["slug"]}.html"/>', h)
    h=re.sub(r'<script type="application/ld\+json">.*?</script>', f'<script type="application/ld+json">{course_schema(c)}</script><script type="application/ld+json">{faq_schema(c)}</script>', h, count=1, flags=re.S)
    main=f'''<main>
<section class="course-simple-hero">
  <div class="container course-simple-grid">
    <div>
      <nav class="breadcrumbs"><a href="index.html">Home</a><span>›</span><a href="courses.html">Courses</a><span>›</span><span>{html.escape(c['title'])}</span></nav>
      <span class="course-type">{html.escape(c['category'])}</span>
      <h1>{html.escape(c['title'])}</h1>
      <p class="course-intro">{html.escape(c['desc'])}</p>
      <div class="course-meta-row">
        <span>⭐ Private 1-to-1 lessons</span><span>🌐 Online classes</span><span>📌 {html.escape(c['level'])}</span>
      </div>
      <div class="hero-actions"><a class="btn btn-primary" href="{wa}" target="_blank" rel="noopener">Enroll on WhatsApp</a><a class="btn btn-outline visible-outline" href="courses.html">View More Classes</a></div>
    </div>
    <aside class="course-enroll-box">
      <div class="course-big-icon">{c['icon']}</div>
      <h2>Course Summary</h2>
      <ul>
        <li><strong>Level:</strong> {html.escape(c['level'])}</li>
        <li><strong>Format:</strong> Online private classes</li>
        <li><strong>Schedule:</strong> Flexible weekly slots</li>
        <li><strong>Contact:</strong> WhatsApp only</li>
      </ul>
      <a class="btn btn-primary full" href="{wa}" target="_blank" rel="noopener">Start Free Trial</a>
    </aside>
  </div>
</section>
<section class="section course-details-section">
  <div class="container course-layout">
    <aside class="course-toc">
      <strong>Course Details</strong>
      <a href="#overview">Overview</a><a href="#learn">What You Will Learn</a><a href="#ideal">Who It Is For</a><a href="#features">Course Features</a><a href="#outcomes">Outcomes</a><a href="#faq">FAQ</a>
    </aside>
    <article class="course-article">
      <section id="overview" class="course-panel"><span class="eyebrow">Overview</span><h2>About this course</h2><p>{html.escape(c['desc'])}</p><p>The lesson is kept simple, clear, and practical. The teacher begins by checking the learner’s current level, then builds a weekly plan with revision, new material, live correction, and homework that the learner can actually maintain.</p></section>
      <section id="learn" class="course-panel"><span class="eyebrow">Learning Objectives</span><h2>What you will learn</h2><ul class="check-list">{learn}</ul></section>
      <section id="ideal" class="course-panel"><span class="eyebrow">Ideal Learners</span><h2>This course is ideal for</h2><ul class="check-list two-col">{ideal}</ul></section>
      <section id="features" class="course-panel"><span class="eyebrow">Course Features</span><h2>Simple, structured, and parent-friendly</h2><div class="feature-grid"><div><strong>Level assessment</strong><p>The teacher checks reading, pronunciation, speed, confidence, and goals before starting.</p></div><div><strong>Private attention</strong><p>Every class focuses on one learner, so mistakes are corrected immediately.</p></div><div><strong>Clear lesson path</strong><p>Students know what they are learning now, what comes next, and what to revise.</p></div><div><strong>Progress updates</strong><p>Parents or adult learners receive simple feedback and next steps.</p></div></div></section>
      <section id="outcomes" class="course-panel"><span class="eyebrow">Expected Outcomes</span><h2>By the end of this course, the learner should be able to</h2><ul class="check-list">{outcomes}</ul></section>
      <section class="course-panel"><span class="eyebrow">Related Classes</span><h2>Continue your learning path</h2><div class="related-pills">{related_html}<a class="related-pill" href="blog.html">Read related articles</a></div></section>
      <section id="faq" class="course-panel"><span class="eyebrow">FAQ</span><h2>Questions about this course</h2><details open><summary>How do I enroll?</summary><p>Click the WhatsApp button and send the student’s age, level, goal, and preferred times.</p></details><details><summary>Can the course be customized?</summary><p>Yes. The teacher can focus on reading, Tajweed, memorization, Arabic, or Islamic Studies depending on the learner’s needs.</p></details><details><summary>Is this suitable for beginners?</summary><p>The course starts with an assessment. If the learner is a complete beginner, the teacher will begin from foundations and move gradually.</p></details></section>
    </article>
  </div>
</section>
<section class="section cta-deep"><div class="container contact-card"><div><span class="eyebrow">Ready to start?</span><h2>Book a trial lesson for {html.escape(c['title'])}</h2><p>Send a WhatsApp message and we will help choose the right level and schedule.</p></div><a class="btn btn-primary" href="{wa}" target="_blank" rel="noopener">Chat on WhatsApp</a></div></section>
'''
    return h+main+footer

for c in courses:
    (root/(c['slug']+'.html')).write_text(course_page(c), encoding='utf-8')

# Build courses.html in the simple clear style with all courses
course_cards=''.join(f'''<a class="course-directory-card" href="{c['slug']}.html"><div class="course-dir-icon">{c['icon']}</div><span>{html.escape(c['category'])}</span><h3>{html.escape(c['title'])}</h3><p>{html.escape(c['desc'])}</p><ul><li>{html.escape(c['level'])}</li><li>Private online classes</li><li>WhatsApp enrollment</li></ul><b>View course details →</b></a>''' for c in courses)
# grouped sections
cats={}
for c in courses:
    key = 'Quran & Tajweed' if c['slug'] in ['quran-reading','noor-al-bayan','noorani-qaida','tajweed','advanced-tajweed','quran-for-kids','quran-for-adults','quran-for-reverts','ijazah-preparation'] else 'Hifz & Revision' if c['slug'] in ['hifz','hifz-revision','juz-amma-revision'] else 'Arabic Courses' if 'arabic' in c['slug'] or c['slug'] in ['conversational-arabic','business-arabic','financial-arabic'] else 'Islamic Studies'
    cats.setdefault(key,[]).append(c)
sections=''
for key, arr in cats.items():
    sections+=f'<section class="course-directory-group"><h2>{html.escape(key)}</h2><div class="course-directory-grid">' + ''.join(f'<a href="{c["slug"]}.html"><span>{c["icon"]}</span><strong>{html.escape(c["title"])}</strong><small>{html.escape(c["level"])}</small></a>' for c in arr) + '</div></section>'

h=set_active(header, 'courses.html')
h=re.sub(r'<title>.*?</title>', '<title>Online Quran, Arabic & Islamic Studies Courses | Quran.com Online Academy</title>', h, flags=re.S)
h=re.sub(r'<meta name="description" content=".*?"/>', '<meta name="description" content="Explore detailed online Quran, Tajweed, Hifz, Quranic Arabic, conversational Arabic, business Arabic, financial Arabic, and Islamic Studies courses with WhatsApp enrollment."/>', h, flags=re.S)
h=re.sub(r'<link rel="canonical" href=".*?"/>', f'<link rel="canonical" href="{base}courses.html"/>', h)
h=re.sub(r'<meta property="og:title" content=".*?"/>', '<meta property="og:title" content="Online Quran, Arabic & Islamic Studies Courses"/>', h)
h=re.sub(r'<meta property="og:description" content=".*?"/>', '<meta property="og:description" content="Choose from Quran Reading, Tajweed, Hifz, Noor Al-Bayan, Quranic Arabic, conversational Arabic, business Arabic, financial Arabic, and Islamic Studies."/>', h)
itemlist=json.dumps({"@context":"https://schema.org","@type":"ItemList","name":"Online Quran and Arabic Courses","itemListElement":[{"@type":"ListItem","position":i+1,"name":c['title'],"url":base+c['slug']+'.html'} for i,c in enumerate(courses)]}, ensure_ascii=False)
h=re.sub(r'<script type="application/ld\+json">.*?</script>', f'<script type="application/ld+json">{itemlist}</script>', h, count=1, flags=re.S)
main=f'''<main>
<section class="course-simple-hero courses-directory-hero"><div class="container course-simple-grid"><div><nav class="breadcrumbs"><a href="index.html">Home</a><span>›</span><span>Courses</span></nav><span class="course-type">Online Quran & Arabic Classes</span><h1>Choose the Right Quran or Arabic Course</h1><p class="course-intro">Simple, clear, detailed course pages for Quran reading, Tajweed, Hifz, Noor Al-Bayan, Quranic Arabic, conversational Arabic, business Arabic, financial Arabic, and Islamic Studies. Every card below opens a full course page with objectives, features, outcomes, and enrollment details.</p><div class="hero-actions"><a class="btn btn-primary" href="{wa}" target="_blank" rel="noopener">Start Free Trial</a><a class="btn btn-outline visible-outline" href="#all-courses">View More Classes</a></div></div><aside class="course-enroll-box"><h2>How to choose</h2><ol><li>Start with the learner’s current level.</li><li>Choose one main goal: reading, recitation, memorization, Arabic, or Islamic Studies.</li><li>Use WhatsApp to request a trial and placement recommendation.</li></ol><a class="btn btn-primary full" href="{wa}" target="_blank" rel="noopener">Ask on WhatsApp</a></aside></div></section>
<section class="section"><div class="container"><div class="section-heading"><span class="eyebrow">Course Directory</span><h2>All available classes</h2><p>Click any course to open a complete detail page.</p></div>{sections}</div></section>
<section id="all-courses" class="section soft"><div class="container"><div class="section-heading"><span class="eyebrow">Detailed Programs</span><h2>Detailed course cards</h2><p>Each course explains what the learner studies, who it is for, expected outcomes, and how to enroll.</p></div><div class="all-course-card-grid">{course_cards}</div></div></section>
<section class="section"><div class="container"><div class="section-heading"><span class="eyebrow">Learning Resources</span><h2>Read related articles</h2><p>Explore hundreds of Quran, Tajweed, Hifz, Arabic, and Islamic Studies guides.</p></div><div class="course-directory-grid"><a href="blog.html"><span>📚</span><strong>All Articles</strong><small>Browse the full blog</small></a><a href="articles/online-quran-classes-for-kids-a-parent-s-complete-guide.html"><span>👧</span><strong>Quran Classes for Kids</strong><small>Parent guide</small></a><a href="articles/how-to-restart-hifz-after-a-long-break-without-feeling-overwhelmed.html"><span>🌙</span><strong>Restart Hifz</strong><small>Memorization guide</small></a><a href="articles/online-tajweed-classes-for-adults-learn-recitation-correctly.html"><span>✨</span><strong>Tajweed for Adults</strong><small>Recitation guide</small></a></div></div></section>
<section class="section cta-deep"><div class="container contact-card"><div><span class="eyebrow">Need help choosing?</span><h2>Send a WhatsApp message and we will recommend the right course</h2><p>Tell us the student’s age, current level, goal, and preferred times.</p></div><a class="btn btn-primary" href="{wa}" target="_blank" rel="noopener">Chat on WhatsApp</a></div></section>
'''
(root/'courses.html').write_text(h+main+footer, encoding='utf-8')

# Update index homepage course links area if matching cards? Replace only course section simple old titles? We'll add a prominent course directory block after trust strip.
index=(root/'index.html').read_text(encoding='utf-8')
if 'id="course-directory-preview"' not in index:
    preview='''<section class="section soft" id="course-directory-preview"><div class="container"><div class="section-heading"><span class="eyebrow">More Classes</span><h2>Explore Quran, Arabic & Islamic Studies courses</h2><p>Every course opens a clear detail page with objectives, ideal learners, features, outcomes, and WhatsApp enrollment.</p></div><div class="course-directory-grid home-course-links"><a href="quran-reading.html"><span>📖</span><strong>Quran Reading</strong><small>Beginner reading foundations</small></a><a href="tajweed.html"><span>✨</span><strong>Tajweed</strong><small>Practical recitation correction</small></a><a href="hifz.html"><span>🌙</span><strong>Hifz</strong><small>Memorization and revision</small></a><a href="arabic.html"><span>🔤</span><strong>Quranic Arabic</strong><small>Vocabulary and grammar</small></a><a href="conversational-arabic.html"><span>💬</span><strong>Conversational Arabic</strong><small>Speak with confidence</small></a><a href="business-arabic.html"><span>💼</span><strong>Business Arabic</strong><small>Professional communication</small></a><a href="financial-arabic.html"><span>💰</span><strong>Financial Arabic</strong><small>Finance vocabulary</small></a><a href="islamic-studies.html"><span>🕌</span><strong>Islamic Studies</strong><small>Aqeedah, Seerah, duas</small></a></div><div class="center-actions"><a class="btn btn-outline visible-outline" href="courses.html">View More Classes</a></div></div></section>'''
    index=index.replace('<section class="section">', preview+'<section class="section">', 1)
(root/'index.html').write_text(index, encoding='utf-8')

# Update sitemap include all course slugs
sm=(root/'sitemap.xml').read_text(encoding='utf-8') if (root/'sitemap.xml').exists() else '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n</urlset>'
urls=set(re.findall(r'<loc>(.*?)</loc>', sm))
lastmod=datetime.date.today().isoformat()
add=''
for c in courses:
    url=base+c['slug']+'.html'
    if url not in urls:
        add+=f'\n  <url><loc>{url}</loc><lastmod>{lastmod}</lastmod><changefreq>monthly</changefreq><priority>0.86</priority></url>'
if add:
    sm=sm.replace('</urlset>', add+'\n</urlset>')
(root/'sitemap.xml').write_text(sm, encoding='utf-8')

# CSS additions
css=(root/'styles.css').read_text(encoding='utf-8')
append='''

/* Simple clear course pages inspired by clean course-directory layouts */
.course-simple-hero { padding: 72px 0 56px; background: linear-gradient(135deg, #fbf7ee 0%, #f3ead9 100%); border-bottom: 1px solid rgba(6,37,31,.1); }
.course-simple-grid { display: grid; grid-template-columns: minmax(0, 1.25fr) minmax(280px, .55fr); gap: 36px; align-items: start; }
.course-type { display:inline-flex; padding: 8px 13px; border-radius:999px; background:#efe1bd; color:#8b691d; font-weight:900; text-transform:uppercase; letter-spacing:.11em; font-size:12px; }
.course-simple-hero h1 { max-width: 860px; font-size: clamp(38px, 5.4vw, 70px) !important; line-height: .98; letter-spacing: -.055em; color: var(--green-950) !important; margin: 18px 0 20px; font-weight: 850; }
.course-intro { max-width: 760px; font-size: clamp(18px, 2vw, 23px); line-height: 1.55; color:#31443f; margin: 0 0 26px; }
.course-meta-row { display:flex; gap:12px; flex-wrap:wrap; margin: 18px 0 28px; }
.course-meta-row span { background:#fff; border:1px solid var(--border); border-radius:999px; padding:10px 14px; font-weight:800; color:#0c4a3f; }
.course-enroll-box { background:#fff; border:1px solid var(--border); border-radius:28px; padding:28px; box-shadow: var(--shadow); position: sticky; top: 105px; }
.course-enroll-box h2 { font-size: 28px; margin: 0 0 12px; }
.course-enroll-box ul, .course-enroll-box ol { padding-left: 22px; color:#4c5d58; }
.course-big-icon { width:78px; height:78px; display:grid; place-items:center; border-radius:24px; font-size:38px; background: var(--gold-soft); margin-bottom:16px; }
.btn.full { width:100%; margin-top: 12px; }
.visible-outline { background:#ffffff !important; color:var(--green-950) !important; border:2px solid rgba(12,74,63,.35) !important; box-shadow:0 12px 28px rgba(12,74,63,.08); }
.course-layout { display:grid; grid-template-columns: 250px minmax(0, 1fr); gap: 34px; align-items:start; }
.course-toc { position:sticky; top:110px; background:#fff; border:1px solid var(--border); border-radius:24px; padding:20px; display:grid; gap:10px; box-shadow:0 18px 48px rgba(7,42,35,.07); }
.course-toc strong { color: var(--green-950); font-size:18px; }
.course-toc a { padding:9px 10px; border-radius:14px; color:#38504a; font-weight:700; }
.course-toc a:hover { background:#f3ead9; color:var(--green-900); }
.course-article { display:grid; gap: 22px; }
.course-panel { background:#fff; border:1px solid var(--border); border-radius:28px; padding:34px; box-shadow:0 18px 48px rgba(7,42,35,.07); }
.course-panel h2 { font-size: clamp(28px, 3vw, 44px); margin:12px 0 16px; }
.course-panel p { color:#4c5d58; font-size:18px; }
.check-list { list-style:none; padding:0; margin: 18px 0 0; display:grid; gap:13px; }
.check-list.two-col { grid-template-columns: repeat(2, minmax(0,1fr)); }
.check-list li { padding:14px 16px 14px 46px; background:#fbf7ee; border:1px solid var(--border); border-radius:18px; position:relative; color:#2d443e; font-weight:650; }
.check-list li::before { content:'✓'; position:absolute; left:16px; top:13px; width:22px; height:22px; display:grid; place-items:center; border-radius:50%; background:var(--green-800); color:#fff; font-size:13px; }
.feature-grid { display:grid; grid-template-columns: repeat(2, minmax(0,1fr)); gap:16px; margin-top:20px; }
.feature-grid div { background:#fbf7ee; border:1px solid var(--border); border-radius:20px; padding:20px; }
.feature-grid strong { display:block; color:var(--green-950); margin-bottom:6px; font-size:18px; }
.feature-grid p { margin:0; font-size:16px; }
.related-pills { display:flex; flex-wrap:wrap; gap:10px; margin-top:16px; }
.related-pill { padding:11px 15px; border-radius:999px; background:#f3ead9; color:var(--green-950); font-weight:850; border:1px solid var(--border); }
.course-panel details { border:1px solid var(--border); border-radius:18px; padding:16px 18px; margin-top:12px; background:#fbf7ee; }
.course-panel summary { cursor:pointer; font-weight:900; color:var(--green-950); }
.course-directory-group { margin: 40px 0; }
.course-directory-group h2 { font-size: clamp(28px, 3vw, 42px); margin-bottom:18px; }
.course-directory-grid { display:grid; grid-template-columns: repeat(4, minmax(0,1fr)); gap:16px; }
.course-directory-grid a { background:#fff; border:1px solid var(--border); border-radius:22px; padding:20px; display:grid; gap:8px; box-shadow:0 14px 34px rgba(7,42,35,.06); transition:.2s ease; }
.course-directory-grid a:hover, .course-directory-card:hover { transform: translateY(-3px); box-shadow:0 22px 55px rgba(7,42,35,.12); border-color: rgba(216,173,72,.55); }
.course-directory-grid span { font-size:30px; }
.course-directory-grid strong { color:var(--green-950); font-size:18px; line-height:1.25; }
.course-directory-grid small { color:var(--muted); font-weight:700; }
.all-course-card-grid { display:grid; grid-template-columns: repeat(3, minmax(0,1fr)); gap:22px; }
.course-directory-card { display:flex; flex-direction:column; gap:12px; background:#fff; border:1px solid var(--border); border-radius:28px; padding:28px; color:inherit; box-shadow:0 18px 48px rgba(7,42,35,.07); transition:.2s ease; }
.course-dir-icon { width:62px; height:62px; display:grid; place-items:center; border-radius:20px; background:var(--gold-soft); font-size:30px; }
.course-directory-card > span { color:var(--gold); font-weight:900; text-transform:uppercase; letter-spacing:.1em; font-size:12px; }
.course-directory-card h3 { font-size:24px; line-height:1.13; }
.course-directory-card p { color:#4c5d58; margin:0; }
.course-directory-card ul { margin:0; padding-left:20px; color:#4c5d58; }
.course-directory-card b { margin-top:auto; color:var(--green-800); }
.center-actions { margin-top:28px; text-align:center; }
.home-course-links { margin-top: 24px; }
@media (max-width: 980px) { .course-simple-grid, .course-layout { grid-template-columns: 1fr; } .course-enroll-box, .course-toc { position: static; } .course-directory-grid { grid-template-columns: repeat(2, minmax(0,1fr)); } .all-course-card-grid { grid-template-columns: 1fr 1fr; } }
@media (max-width: 640px) { .course-simple-hero h1 { font-size: clamp(34px, 12vw, 50px) !important; } .course-directory-grid, .all-course-card-grid, .feature-grid, .check-list.two-col { grid-template-columns: 1fr; } .course-panel { padding:24px; } }
'''
if 'Simple clear course pages inspired' not in css:
    css += append
(root/'styles.css').write_text(css, encoding='utf-8')

print('updated', len(courses), 'course pages')
